spring.application.name=app

# JBossのJNDIデータソースを使う
spring.datasource.jndi-name=java:/PostgresDS

#M MyBatis設定
mybatis.mapper-locations=classpath:/mapper/*.xml
mybatis.type-aliases-package=task2.app.entity